--
-- PostgreSQL database dump
--

-- Dumped from database version 16.1
-- Dumped by pg_dump version 16.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: allergy; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.allergy (
    allergy_id bigint NOT NULL,
    student_id bigint NOT NULL,
    allergy_name character varying(255),
    allergy_description text
);


ALTER TABLE public.allergy OWNER TO postgres;

--
-- Name: allergy_allergy_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.allergy ALTER COLUMN allergy_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.allergy_allergy_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: class; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.class (
    grade integer,
    totalstudent integer DEFAULT 0,
    class_id bigint NOT NULL,
    class_name character varying(100)
);


ALTER TABLE public.class OWNER TO postgres;

--
-- Name: class_class_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.class ALTER COLUMN class_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.class_class_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: content; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.content (
    content_category_id bigint,
    content_id bigint NOT NULL,
    title character varying(255),
    body_content text
);


ALTER TABLE public.content OWNER TO postgres;

--
-- Name: content_category; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.content_category (
    content_category_id bigint NOT NULL,
    content_category_name character varying(255)
);


ALTER TABLE public.content_category OWNER TO postgres;

--
-- Name: content_category_content_category_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.content_category ALTER COLUMN content_category_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.content_category_content_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: content_content_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.content ALTER COLUMN content_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.content_content_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: health_check; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.health_check (
    check_date date NOT NULL,
    height_cm numeric(5,2),
    weight_kg numeric(5,2),
    created_at timestamp(6) with time zone,
    health_check_id bigint NOT NULL,
    student_id bigint NOT NULL,
    updated_at timestamp(6) with time zone,
    vision_left character varying(10),
    vision_right character varying(10),
    blood_pressure character varying(20),
    hearing character varying(100),
    dental_health text,
    notes text,
    other_conditions text,
    skin_health text
);


ALTER TABLE public.health_check OWNER TO postgres;

--
-- Name: health_check_health_check_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.health_check ALTER COLUMN health_check_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.health_check_health_check_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: medical_records; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.medical_records (
    medical_record_id bigint NOT NULL,
    medical_type character varying(255),
    medical_description text
);


ALTER TABLE public.medical_records OWNER TO postgres;

--
-- Name: medical_records_medical_record_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.medical_records ALTER COLUMN medical_record_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.medical_records_medical_record_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: medication; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.medication (
    prescription_required boolean,
    medication_id bigint NOT NULL,
    country_of_origin character varying(100),
    dosage_form character varying(100),
    category character varying(255),
    description character varying(255),
    medication_information character varying(255),
    medication_name character varying(255),
    medication_img text
);


ALTER TABLE public.medication OWNER TO postgres;

--
-- Name: medication_medication_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.medication ALTER COLUMN medication_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.medication_medication_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notifications (
    date_create date NOT NULL,
    notification_id bigint NOT NULL,
    user_id bigint NOT NULL,
    content character varying(255) NOT NULL,
    status character varying(255),
    title character varying(255) NOT NULL,
    CONSTRAINT notifications_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'VERIFY'::character varying, 'BAN'::character varying, 'DELETED'::character varying])::text[])))
);


ALTER TABLE public.notifications OWNER TO postgres;

--
-- Name: notifications_notification_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notifications ALTER COLUMN notification_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: parent; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.parent (
    parent_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.parent OWNER TO postgres;

--
-- Name: parent_parent_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.parent ALTER COLUMN parent_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.parent_parent_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: prescription; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.prescription (
    end_date date,
    start_date date,
    created_at timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP,
    nurse_id bigint NOT NULL,
    prescription_id bigint NOT NULL,
    student_id bigint NOT NULL,
    updated_at timestamp(6) with time zone,
    status character varying(50)
);


ALTER TABLE public.prescription OWNER TO postgres;

--
-- Name: prescription_detail; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.prescription_detail (
    quantity integer DEFAULT 1,
    medication_id bigint NOT NULL,
    prescription_detail_id bigint NOT NULL,
    prescription_id bigint NOT NULL,
    dosage text,
    instructions text
);


ALTER TABLE public.prescription_detail OWNER TO postgres;

--
-- Name: prescription_detail_prescription_detail_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.prescription_detail ALTER COLUMN prescription_detail_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.prescription_detail_prescription_detail_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: prescription_prescription_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.prescription ALTER COLUMN prescription_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.prescription_prescription_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: student; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.student (
    class_id bigint,
    parent_id bigint,
    student_id bigint NOT NULL,
    user_id bigint NOT NULL,
    genetic_disease text
);


ALTER TABLE public.student OWNER TO postgres;

--
-- Name: student_medical_record; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.student_medical_record (
    medical_date date,
    medical_record_id bigint NOT NULL,
    student_id bigint NOT NULL,
    student_medical_record_id bigint NOT NULL,
    medical_result text
);


ALTER TABLE public.student_medical_record OWNER TO postgres;

--
-- Name: student_medical_record_student_medical_record_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.student_medical_record ALTER COLUMN student_medical_record_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_medical_record_student_medical_record_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: student_student_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.student ALTER COLUMN student_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_student_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: student_vaccination; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.student_vaccination (
    vaccination_date date,
    student_id bigint NOT NULL,
    student_vaccination_id bigint NOT NULL,
    vaccination_id bigint NOT NULL,
    vaccination_result text
);


ALTER TABLE public.student_vaccination OWNER TO postgres;

--
-- Name: student_vaccination_student_vaccination_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.student_vaccination ALTER COLUMN student_vaccination_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_vaccination_student_vaccination_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."user" (
    dob date,
    role_name smallint,
    user_id bigint NOT NULL,
    gender character varying(10),
    phone character varying(20) NOT NULL,
    address character varying(255),
    email character varying(255),
    fullname character varying(255),
    status character varying(255),
    username character varying(255),
    avatarurl text,
    password text,
    CONSTRAINT user_role_name_check CHECK (((role_name >= 0) AND (role_name <= 1))),
    CONSTRAINT user_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'VERIFY'::character varying, 'BAN'::character varying, 'DELETED'::character varying])::text[])))
);


ALTER TABLE public."user" OWNER TO postgres;

--
-- Name: user_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."user" ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vaccination_records; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.vaccination_records (
    vaccination_id bigint NOT NULL,
    vaccination_type character varying(255),
    vaccination_description text
);


ALTER TABLE public.vaccination_records OWNER TO postgres;

--
-- Name: vaccination_records_vaccination_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.vaccination_records ALTER COLUMN vaccination_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vaccination_records_vaccination_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: allergy allergy_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.allergy
    ADD CONSTRAINT allergy_pkey PRIMARY KEY (allergy_id);


--
-- Name: class class_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.class
    ADD CONSTRAINT class_pkey PRIMARY KEY (class_id);


--
-- Name: content_category content_category_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.content_category
    ADD CONSTRAINT content_category_pkey PRIMARY KEY (content_category_id);


--
-- Name: content content_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.content
    ADD CONSTRAINT content_pkey PRIMARY KEY (content_id);


--
-- Name: health_check health_check_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.health_check
    ADD CONSTRAINT health_check_pkey PRIMARY KEY (health_check_id);


--
-- Name: medical_records medical_records_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.medical_records
    ADD CONSTRAINT medical_records_pkey PRIMARY KEY (medical_record_id);


--
-- Name: medication medication_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.medication
    ADD CONSTRAINT medication_pkey PRIMARY KEY (medication_id);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (notification_id);


--
-- Name: parent parent_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.parent
    ADD CONSTRAINT parent_pkey PRIMARY KEY (parent_id);


--
-- Name: parent parent_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.parent
    ADD CONSTRAINT parent_user_id_key UNIQUE (user_id);


--
-- Name: prescription_detail prescription_detail_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescription_detail
    ADD CONSTRAINT prescription_detail_pkey PRIMARY KEY (prescription_detail_id);


--
-- Name: prescription prescription_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescription
    ADD CONSTRAINT prescription_pkey PRIMARY KEY (prescription_id);


--
-- Name: student_medical_record student_medical_record_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_medical_record
    ADD CONSTRAINT student_medical_record_pkey PRIMARY KEY (student_medical_record_id);


--
-- Name: student student_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student
    ADD CONSTRAINT student_pkey PRIMARY KEY (student_id);


--
-- Name: student student_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student
    ADD CONSTRAINT student_user_id_key UNIQUE (user_id);


--
-- Name: student_vaccination student_vaccination_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_vaccination
    ADD CONSTRAINT student_vaccination_pkey PRIMARY KEY (student_vaccination_id);


--
-- Name: user user_phone_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_phone_key UNIQUE (phone);


--
-- Name: user user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_pkey PRIMARY KEY (user_id);


--
-- Name: vaccination_records vaccination_records_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vaccination_records
    ADD CONSTRAINT vaccination_records_pkey PRIMARY KEY (vaccination_id);


--
-- Name: student_vaccination fk1x1wy9fuoyolnqf5e4fh4f5m1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_vaccination
    ADD CONSTRAINT fk1x1wy9fuoyolnqf5e4fh4f5m1 FOREIGN KEY (student_id) REFERENCES public.student(student_id) ON DELETE CASCADE;


--
-- Name: notifications fk3dt2b80521eynbjg4nehtjnhy; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT fk3dt2b80521eynbjg4nehtjnhy FOREIGN KEY (user_id) REFERENCES public."user"(user_id);


--
-- Name: prescription fkasewaibksbvxueo8vq0u84erf; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescription
    ADD CONSTRAINT fkasewaibksbvxueo8vq0u84erf FOREIGN KEY (student_id) REFERENCES public.student(student_id) ON DELETE CASCADE;


--
-- Name: prescription_detail fkdq2yagbksdomo6t1o1b8g3poe; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescription_detail
    ADD CONSTRAINT fkdq2yagbksdomo6t1o1b8g3poe FOREIGN KEY (prescription_id) REFERENCES public.prescription(prescription_id) ON DELETE CASCADE;


--
-- Name: student fkdwhkib64u47wc4yo4hk0cub90; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student
    ADD CONSTRAINT fkdwhkib64u47wc4yo4hk0cub90 FOREIGN KEY (class_id) REFERENCES public.class(class_id);


--
-- Name: student_medical_record fkek5v7up1rt5kaj0nc9xef68eh; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_medical_record
    ADD CONSTRAINT fkek5v7up1rt5kaj0nc9xef68eh FOREIGN KEY (medical_record_id) REFERENCES public.medical_records(medical_record_id) ON DELETE CASCADE;


--
-- Name: content fkeyxy4ro24vgxliuuvkq0lwrg6; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.content
    ADD CONSTRAINT fkeyxy4ro24vgxliuuvkq0lwrg6 FOREIGN KEY (content_category_id) REFERENCES public.content_category(content_category_id);


--
-- Name: prescription_detail fkhlg2f0qtitf18xw3e4jfyoi8q; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescription_detail
    ADD CONSTRAINT fkhlg2f0qtitf18xw3e4jfyoi8q FOREIGN KEY (medication_id) REFERENCES public.medication(medication_id);


--
-- Name: student_vaccination fkiut2i923jiifdn626tx1miy7v; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_vaccination
    ADD CONSTRAINT fkiut2i923jiifdn626tx1miy7v FOREIGN KEY (vaccination_id) REFERENCES public.vaccination_records(vaccination_id) ON DELETE CASCADE;


--
-- Name: student fkk5m148xqefonqw7bgnpm0snwj; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student
    ADD CONSTRAINT fkk5m148xqefonqw7bgnpm0snwj FOREIGN KEY (user_id) REFERENCES public."user"(user_id);


--
-- Name: parent fkl4w905h1321m2ide56ov5efb0; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.parent
    ADD CONSTRAINT fkl4w905h1321m2ide56ov5efb0 FOREIGN KEY (user_id) REFERENCES public."user"(user_id);


--
-- Name: health_check fkpqnmyp4b42uwvwxq8qhlx3ge4; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.health_check
    ADD CONSTRAINT fkpqnmyp4b42uwvwxq8qhlx3ge4 FOREIGN KEY (student_id) REFERENCES public.student(student_id) ON DELETE CASCADE;


--
-- Name: prescription fkqehitf3ukg1vciifj9im7tmd2; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescription
    ADD CONSTRAINT fkqehitf3ukg1vciifj9im7tmd2 FOREIGN KEY (nurse_id) REFERENCES public."user"(user_id);


--
-- Name: student fkqqq09m02bgrk47qoe6fs3ht4w; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student
    ADD CONSTRAINT fkqqq09m02bgrk47qoe6fs3ht4w FOREIGN KEY (parent_id) REFERENCES public.parent(parent_id) ON DELETE CASCADE;


--
-- Name: student_medical_record fkrng4goepexfuyhrt5ymxwkuib; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_medical_record
    ADD CONSTRAINT fkrng4goepexfuyhrt5ymxwkuib FOREIGN KEY (student_id) REFERENCES public.student(student_id) ON DELETE CASCADE;


--
-- Name: allergy fksqqfx588knubem5x6ivdw76x9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.allergy
    ADD CONSTRAINT fksqqfx588knubem5x6ivdw76x9 FOREIGN KEY (student_id) REFERENCES public.student(student_id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

