spring.application.name=School_Medical_System

spring.jpa.open-in-view=false

spring.datasource.url=jdbc:postgresql://dpg-d1t0fc6r433s73er6fhg-a.singapore-postgres.render.com:5432/school_medical_db_n3q3?sslmode=require
spring.datasource.username=hoangnq
spring.datasource.password=NsuI4c2r5P7rQzW03o3kM2DqynTkfFR6
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate ki?m tra schema ?ã ?úng ch?a
spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.data-source-properties.ssl=true
spring.datasource.hikari.data-source-properties.sslmode=require



spring.data.redis.host=switchback.proxy.rlwy.net
spring.data.redis.port=10064
spring.data.redis.username=default
spring.data.redis.password=rzYsssVbVgYCXqSqXwzAeGrQEeOgNewc

spring.mail.default-encoding=UTF-8
spring.mail.host=smtp.gmail.com

jwt.secret=cf4XDJFQiu1Bdtxh5CJBeLBxH5HYlcuOGlo127VQ7E40vR7dhiqkl3w7lfvVGtk6BumPmHpu5Xy1jp7wAzROX6LBIFYWtKhXQCQKKjv3s28eQEpkST91sRY3XwgxqJRh

logging.level.org.hibernate.orm.boot.spi.BootstrapContextImpl=ERROR
logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=ERROR
logging.level.org.springframework.data.repository.config.RepositoryConfigurationExtensionSupport=ERROR
